name       : radeon-profile
version    : '20200824'
release    : 7
source     :
    - https://github.com/marazmista/radeon-profile/archive/20200824.tar.gz : 8d378d8ba249f2655783798b8e86ce1eb7a9a1dcd12d29784ba40366583b47af
license    : GPL-2.0-or-later
component  : system.utils
summary    : GUI for configuring AMD video cards
description: |
    A GUI application for configuring AMD video cards using mesalib. Supports overclocking, fan control, and basic monitoring.
builddeps  :
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(Qt5Charts)
    - pkgconfig(xrandr)
rundeps    :
    - radeon-profile-daemon
setup      : |
    cd radeon-profile
    %qmake
    echo "INSTALL_ROOT=$installdir" >> Makefile
build      : |
    cd radeon-profile
    %make
install    : |
    cd radeon-profile
    %make_install
