name       : radeon-profile
version    : '20200504'
release    : 5
source     :
    - https://github.com/marazmista/radeon-profile/archive/20200504.tar.gz : 4f9880e31862419d11a2b860893e69bfd70afab8397b00ed774c54b5a21760b0
license    : GPL-2.0-or-later
component  : system.utils
summary    : GUI for configuring AMD video cards
description: |
    A GUI application for configuring AMD video cards using mesalib. Supports overclocking, fan control, and basic monitoring.
builddeps  :
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(Qt5Charts)
    - pkgconfig(xrandr)
rundeps    :
    - radeon-profile-daemon
setup      : |
    cd radeon-profile
    %qmake
    echo "INSTALL_ROOT=$installdir" >> Makefile
build      : |
    cd radeon-profile
    %make
install    : |
    cd radeon-profile
    %make_install
