name       : radeon-profile
version    : '20190603'
release    : 3
source     :
    - https://github.com/marazmista/radeon-profile/archive/20190603.tar.gz : f027d2dcc3278a8ce684778359310ee02ee7c79fa5c4ecc56e636a4020bdeeed
license    : GPL-2.0-or-later
component  : system.utils
summary    : GUI for configuring AMD video cards
description: |
    A GUI application for configuring AMD video cards using mesalib. Supports overclocking, fan control, and basic monitoring.
builddeps  :
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(Qt5Charts)
    - pkgconfig(xrandr)
rundeps    :
    - radeon-profile-daemon
setup      : |
    cd radeon-profile
    %qmake
    echo "INSTALL_ROOT=$installdir" >> Makefile
build      : |
    cd radeon-profile
    %make
install    : |
    cd radeon-profile
    %make_install
