name       : radeon-profile
version    : 20190220
release    : 1
source     :
    - https://github.com/marazmista/radeon-profile/archive/20190220.tar.gz : d1ff606839594e0a8de049cde9e0d8c4cd97b260997a55aa7c2c95d0b2be22ff
license    : GPL-2.0-or-later
component  : system.utils
summary    : GUI for configuring AMD video cards
description: |
    A GUI application for configuring AMD video cards using mesalib. Supports overclocking, fan control, and basic monitoring.
builddeps  :
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(Qt5Charts)
    - pkgconfig(xrandr)
rundeps    :
    - radeon-profile-daemon
setup      : |
    cd radeon-profile
    %qmake
    echo "INSTALL_ROOT=$installdir" >> Makefile
build      : |
    cd radeon-profile
    %make
install    : |
    cd radeon-profile
    %make_install
