name       : radeon-profile
version    : '20190311'
release    : 2
source     :
    - https://github.com/marazmista/radeon-profile/archive/20190311.tar.gz : 0347705897900c100f320c487befe6e1e56ba2f53b93dbecc166bbd3e9434a78
license    : GPL-2.0-or-later
component  : system.utils
summary    : GUI for configuring AMD video cards
description: |
    A GUI application for configuring AMD video cards using mesalib. Supports overclocking, fan control, and basic monitoring.
builddeps  :
    - pkgconfig(libdrm_amdgpu)
    - pkgconfig(Qt5Charts)
    - pkgconfig(xrandr)
rundeps    :
    - radeon-profile-daemon
setup      : |
    cd radeon-profile
    %qmake
    echo "INSTALL_ROOT=$installdir" >> Makefile
build      : |
    cd radeon-profile
    %make
install    : |
    cd radeon-profile
    %make_install
